apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: platform-dev
patches:
  - path: patch-replicas.yaml
  - path: patch-ingress.yaml
  - path: patch-config.yaml
images:
  - name: platform-scaffolded-api
    newTag: e67f4b47b536e48cdfacca054a7562c15559f4ef
    newName: p6hi/platform-scaffolded-api
