apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-scaffolded-api
  labels:
    app: platform-scaffolded-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-scaffolded-api
  template:
    metadata:
      labels:
        app: platform-scaffolded-api
    spec:
      serviceAccountName: platform-scaffolded-api-service-account
      automountServiceAccountToken: false
      containers:
        - name: platform-scaffolded-api
          image: platform-scaffolded-api
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: metrics
              containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: platform-scaffolded-api-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
