apiVersion: v1
kind: Service
metadata:
  name: platform-scaffolded-api
  labels:
    app: platform-scaffolded-api
    team: platform
spec:
  selector:
    app: platform-scaffolded-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: metrics
      protocol: TCP
      port: 3000
      targetPort: metrics
